version: "3.8"

services:
  server:
    image: turn
    deploy:
      replicas: 1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - 3478:3478
    command: --addr :3478
